replicaCount: 3

image:
  repository: your-registry/modelbackend
  tag: stable
  pullPolicy: Always

resources:
  limits:
    memory: "2Gi"
    cpu: "500m"
  requests:
    memory: "1Gi"
    cpu: "200m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

redis:
  secretName: redis-secret-prod