# web-server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: webfrontend:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
          - containerPort: 80
        env:
        - name: NEXT_PUBLIC_MODEL_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: web-server-config
              key: NEXT_PUBLIC_MODEL_SERVER_URL

---

# web-server service
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP