# web-server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: frontend:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
          - containerPort: 80
        env:
          - name: REDIS_HOST
            value: redis-db-service
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            value: rediscache

---

# web-server service
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
  - port: 80
    targetPort: 80